FROM php:7.4-fpm-alpine

# Install necessary packages
RUN apk add --no-cache nginx wget nodejs npm

# Install Yarn
RUN npm install -g yarn

# Create necessary directories
RUN mkdir -p /run/nginx /app

# Copy Nginx configuration
COPY docker/nginx.conf /etc/nginx/nginx.conf

# Copy application files
COPY . /app

# Install Composer
RUN wget http://getcomposer.org/composer.phar && chmod a+x composer.phar && mv composer.phar /usr/local/bin/composer

# Install PHP dependencies
RUN cd /app && composer install --no-dev

# Install JavaScript dependencies and compile assets
RUN cd /app && yarn install && yarn production

# Set ownership for the application directory
RUN chown -R www-data: /app

# Start services
CMD sh /app/docker/startup.sh